version: "3.9"

services:
  api:
    image: backend-a12022:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      ENV: development
      UVICORN_RELOAD: "true"
      # DATABASE_URL: postgresql://USER:PASS@HOST/DB?sslmode=require
      # JWT_SECRET_KEY: troque-por-chave-segura
      # STORAGE_PROVIDER: local
      # AUTH_MODE: local
      # EMAIL_PROVIDER: dev
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
      --lifespan off
