[global]
timeout = 1000

index-url = https://jfrog.petrobras.dev.br/artifactory/api/pypi/pypi-group-all/simple

# opcional, mas recomendado como fallback:
extra-index-url = https://jfrog.petrobras.dev.br/artifactory/api/pypi/pypi-group/simple

trusted-host = jfrog.petrobras.dev.br
 