env:
  Repository: a12022
  Name: scac

build:
  python:
    #Name: "a12022-backend"
    Name: "scac"
    PythonVersion: "3.12"
    PythonSourcePath: "."
    DependenciesManager: "pip"
    TestingTool: "pytest"
    SkipTests: false
    SonarSources: app

  docker:
    RegistryName: ecr
    Dockerfile: ./Dockerfile

upload:
  docker:

deploy:
  SnapshotEnvs: DSV
 # StartReleaseEnvs: HMG
