env:
  Repository: a12022
  Name: scac

build:
  python:
    Name: "scac"
    PythonVersion: "3.13"
    PythonSourcePath: "."
    DependenciesManager: "pip"
    TestingTool: "pytest"
    SkipTests: false
    SonarSources: app

  docker:
    Name: scac
    RegistryName: ecr
    Repository: a12022
    Dockerfile: ./Dockerfile
    ContextRoot: .

  dotnet:
    ProjectName: mip-sdk-worker
    SolutionName: mip-sdk-worker
    Name: mip-sdk-worker
    RegistryName: ecr
    Repository: a12022
    DockerfileFolder: mip-sdk-worker

upload:
  docker:
    RegistryName: ecr
    Repository: a12022
    Images:
      - scac
      
  dotnet:
    RegistryName: ecr
    Repository: a12022
    Images:
      - mip-sdk-worker

deploy:
  SnapshotEnvs: DSV, TST
  StartReleaseEnvs: HMG
