env:
  Repository: frontend
  Name: csa-frontend

build:
  node:
    Name: "a12022-frontend"
    NodeVersion: "20"
    NodeSourcePath: "."
    PackageManager: "npm"
    SkipTests: true

  docker:
    RegistryName: ecr
    Dockerfile: ./Dockerfile

upload:
  docker:
