"""add_login_cav4_to_user

Revision ID: a50765295044
Revises: bd7ab86e7ecc
Create Date: 2026-06-30 01:49:31.591107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a50765295044'
down_revision: Union[str, Sequence[str], None] = 'bd7ab86e7ecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login_cav4', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_user_login_cav4'), 'user', ['login_cav4'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_login_cav4'), table_name='user')
    op.drop_column('user', 'login_cav4')
    # ### end Alembic commands ###
