"""initial

Revision ID: e9662255fe47
Revises: 
Create Date: 2026-05-15 15:34:51.192393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9662255fe47'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('EXTERNAL', 'INTERNAL', name='typeuser'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('job_title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('employee_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('is_supervisor', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_type'), ['type'], unique=False)

    op.create_table('credential_local',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('salt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('blocked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credential_local', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credential_local_blocked_until'), ['blocked_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_credential_local_failed_attempts'), ['failed_attempts'], unique=False)
        batch_op.create_index(batch_op.f('ix_credential_local_user_id'), ['user_id'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('INFO', 'SUCCESS', 'WARNING', 'ERROR', 'APPROVAL', 'REJECTION', 'DOWNLOAD', 'EXPIRATION', name='notificationtype'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='notificationpriority'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('action_label', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('action_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('extra_metadata', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_read'), ['read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    op.create_table('session_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_type', sa.Enum('REFRESH', 'RESET', name='tokentype'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_token_token_hash'), ['token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_token_token_type'), ['token_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_token_user_id'), ['user_id'], unique=False)

    op.create_table('shared_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prefix_s3', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shared_area', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shared_area_applicant_id'), ['applicant_id'], unique=False)

    op.create_table('support_registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('requester_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('external_user_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('external_user_id', sa.Integer(), nullable=True),
    sa.Column('registered_by_id', sa.Integer(), nullable=False),
    sa.Column('registered_by_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'PENDENTE', 'INATIVO', 'CANCELADO', name='supportregistrationstatus'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_reactivation', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['external_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['registered_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_registration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_registration_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_registration_external_user_email'), ['external_user_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_registration_registered_by_id'), ['registered_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_registration_request_number'), ['request_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_registration_requester_email'), ['requester_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_registration_status'), ['status'], unique=False)

    op.create_table('areasupervisor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['shared_area.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('areasupervisor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_areasupervisor_area_id'), ['area_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_areasupervisor_supervisor_id'), ['supervisor_id'], unique=False)

    op.create_table('restricted_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_s3', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('checksum', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('upload_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['shared_area.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('external_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'APPROVED', 'REJECTED', 'COMPLETED', 'EXPIRED', 'CANCELED', name='sharestatus'), nullable=False),
    sa.Column('consumption_policy', sa.Enum('AFTER_ALL', 'AFTER_FIRST', name='tokenconsumption'), nullable=False),
    sa.Column('expiration_hours', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('approval_comments', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['area_id'], ['shared_area.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('share', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_area_id'), ['area_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_external_email'), ['external_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_status'), ['status'], unique=False)

    op.create_table('support_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CADASTRO', 'REATIVACAO', 'INATIVACAO', 'ALTERACAO', 'CONSULTA', name='supportaction'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('support_user_id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=True),
    sa.Column('affected_user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['affected_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['registration_id'], ['support_registration.id'], ),
    sa.ForeignKeyConstraint(['support_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_audit_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_audit_affected_user_id'), ['affected_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_audit_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_audit_registration_id'), ['registration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_audit_support_user_id'), ['support_user_id'], unique=False)

    op.create_table('audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('level', sa.Enum('INFO', 'SUCCESS', 'WARNING', 'ERROR', name='typelevel'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('share_id', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['restricted_file.id'], ),
    sa.ForeignKeyConstraint(['share_id'], ['share.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_share_id'), ['share_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_user_id'), ['user_id'], unique=False)

    op.create_table('email_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email_type', sa.Enum('FILE_SHARE', 'OTP', 'APPROVAL_REQUEST', 'APPROVAL_GRANTED', 'APPROVAL_REJECTED', 'EXPIRATION_WARNING', 'DOWNLOAD_CONFIRMATION', 'PASSWORD_RESET', 'WELCOME', 'SYSTEM', name='emailtype'), nullable=False),
    sa.Column('from_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('to_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body_preview', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'SENT', 'DELIVERED', 'OPENED', 'CLICKED', 'BOUNCED', 'COMPLAINED', 'FAILED', name='emailstatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('bounced_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('share_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('extra_metadata', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['share_id'], ['share.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_log_email_type'), ['email_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_log_message_id'), ['message_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_email_log_share_id'), ['share_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_log_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_log_to_email'), ['to_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_log_user_id'), ['user_id'], unique=False)

    op.create_table('share_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('share_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('downloaded', sa.Boolean(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['restricted_file.id'], ),
    sa.ForeignKeyConstraint(['share_id'], ['share.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('share_file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_file_downloaded'), ['downloaded'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_file_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_share_file_share_id'), ['share_id'], unique=False)

    op.create_table('token_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('OTP', 'ACCESS', name='typetoken'), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('share_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('blocked_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['share_id'], ['share.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_access_attempts'), ['attempts'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_access_blocked_until'), ['blocked_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_access_share_id'), ['share_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_access_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_token_access_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_access_used'), ['used'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_access_user_id'), ['user_id'], unique=False)

    # Remove a tabela de controle do Flyway (se existir).
    # O índice pode não estar presente em todos os ambientes, por isso
    # verificamos antes de tentar remover.
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'SCHEMA_VERSION_DEPLOYBD' in inspector.get_table_names():
        existing_indexes = [
            idx['name'] for idx in inspector.get_indexes('SCHEMA_VERSION_DEPLOYBD')
        ]
        if 'SCHEMA_VERSION_DEPLOYBD_s_idx' in existing_indexes:
            op.drop_index('SCHEMA_VERSION_DEPLOYBD_s_idx', table_name='SCHEMA_VERSION_DEPLOYBD')
        op.drop_table('SCHEMA_VERSION_DEPLOYBD')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SCHEMA_VERSION_DEPLOYBD',
    sa.Column('installed_rank', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('script', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('installed_by', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('installed_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('execution_time', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('installed_rank', name=op.f('SCHEMA_VERSION_DEPLOYBD_pk'))
    )
    with op.batch_alter_table('SCHEMA_VERSION_DEPLOYBD', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('SCHEMA_VERSION_DEPLOYBD_s_idx'), ['success'], unique=False)

    with op.batch_alter_table('token_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_access_user_id'))
        batch_op.drop_index(batch_op.f('ix_token_access_used'))
        batch_op.drop_index(batch_op.f('ix_token_access_type'))
        batch_op.drop_index(batch_op.f('ix_token_access_token'))
        batch_op.drop_index(batch_op.f('ix_token_access_share_id'))
        batch_op.drop_index(batch_op.f('ix_token_access_blocked_until'))
        batch_op.drop_index(batch_op.f('ix_token_access_attempts'))

    op.drop_table('token_access')
    with op.batch_alter_table('share_file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_file_share_id'))
        batch_op.drop_index(batch_op.f('ix_share_file_file_id'))
        batch_op.drop_index(batch_op.f('ix_share_file_downloaded'))

    op.drop_table('share_file')
    with op.batch_alter_table('email_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_log_to_email'))
        batch_op.drop_index(batch_op.f('ix_email_log_status'))
        batch_op.drop_index(batch_op.f('ix_email_log_share_id'))
        batch_op.drop_index(batch_op.f('ix_email_log_message_id'))
        batch_op.drop_index(batch_op.f('ix_email_log_email_type'))

    op.drop_table('email_log')
    with op.batch_alter_table('audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_share_id'))
        batch_op.drop_index(batch_op.f('ix_audit_level'))
        batch_op.drop_index(batch_op.f('ix_audit_file_id'))

    op.drop_table('audit')
    with op.batch_alter_table('support_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_audit_support_user_id'))
        batch_op.drop_index(batch_op.f('ix_support_audit_registration_id'))
        batch_op.drop_index(batch_op.f('ix_support_audit_created_at'))
        batch_op.drop_index(batch_op.f('ix_support_audit_affected_user_id'))
        batch_op.drop_index(batch_op.f('ix_support_audit_action'))

    op.drop_table('support_audit')
    with op.batch_alter_table('share', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_status'))
        batch_op.drop_index(batch_op.f('ix_share_external_email'))
        batch_op.drop_index(batch_op.f('ix_share_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_share_area_id'))

    op.drop_table('share')
    op.drop_table('restricted_file')
    with op.batch_alter_table('areasupervisor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_areasupervisor_supervisor_id'))
        batch_op.drop_index(batch_op.f('ix_areasupervisor_area_id'))

    op.drop_table('areasupervisor')
    with op.batch_alter_table('support_registration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_registration_status'))
        batch_op.drop_index(batch_op.f('ix_support_registration_requester_email'))
        batch_op.drop_index(batch_op.f('ix_support_registration_request_number'))
        batch_op.drop_index(batch_op.f('ix_support_registration_registered_by_id'))
        batch_op.drop_index(batch_op.f('ix_support_registration_external_user_email'))
        batch_op.drop_index(batch_op.f('ix_support_registration_created_at'))

    op.drop_table('support_registration')
    with op.batch_alter_table('shared_area', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shared_area_applicant_id'))

    op.drop_table('shared_area')
    with op.batch_alter_table('session_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_token_user_id'))
        batch_op.drop_index(batch_op.f('ix_session_token_token_type'))
        batch_op.drop_index(batch_op.f('ix_session_token_token_hash'))

    op.drop_table('session_token')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_type'))
        batch_op.drop_index(batch_op.f('ix_notification_read'))

    op.drop_table('notification')
    with op.batch_alter_table('credential_local', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credential_local_user_id'))
        batch_op.drop_index(batch_op.f('ix_credential_local_failed_attempts'))
        batch_op.drop_index(batch_op.f('ix_credential_local_blocked_until'))

    op.drop_table('credential_local')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_type'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
