# Para mais informações sobre a configuração do arquivo deploy-config.yml,
# acesse https://rigs.petrobras.com.br/docs/default/component/d9i3-templates/deploy-config-yml

################################################################################################

serverType: aws

artifacts:

  backend:
    CdkStack: ecs-task
    CdkAppServiceName: backend
    CdkAppServiceImageName: scac
    CdkAppServiceRule: /api/v1/*
    CdkAppServiceContainerPort: 8080
    CdkAppServiceTaskCpu: 1024
    CdkAppServiceTaskMemory: 2048
    CdkAppServiceHealthCheckPath: /api/v1
    CdkAppServiceHealthCheckGracePeriod: 200
    CdkAppServiceHealthCheckInterval: 60
    CdkAppServiceHealthCheckTimeout: 30
    CdkAppServiceUnhealthThresholdCount: 5
    CdkBucketName: a12022-s3
    CdkBucketPermissions: '["READ","WRITE"]'


  mip-wrkr:
    CdkStack: ecs-task
    CdkAppServiceName: mip-worker
    CdkAppServiceImageName: mip-sdk-worker      
    CdkAppServiceRule: /mip-worker/* 
    CdkAppServiceContainerPort: 8081 
    CdkAppServiceTaskCpu: 512
    CdkAppServiceTaskMemory: 1024
    CdkAppServiceHealthCheckPath: /mip-worker/health
    CdkAppServiceHealthCheckGracePeriod: 120
    CdkAppServiceHealthCheckInterval: 60
    CdkAppServiceHealthCheckTimeout: 30
    CdkAppServiceUnhealthThresholdCount: 5

envs:
  DSV:
    backend:
      CdkAppServiceRulePriority: 11
    mip-wrkr:
      CdkAppServiceRulePriority: 21

  TST:
    backend:
      CdkAppServiceRulePriority: 12
    mip-wrkr:
      CdkAppServiceRulePriority: 22

  HMG:
    backend:
      CdkAppServiceRulePriority: 13
    mip-wrkr:
      CdkAppServiceRulePriority: 23

  PRD:
    backend:
      CdkAppServiceRulePriority: 13
    mip-wrkr:
      CdkAppServiceRulePriority: 23 
